### ISSUE TITLE
Make site header be pretty on desktop

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#1]
The banner shall be visible on all pages.

It has three tiers: 

* 1st is the Praqma logo - centered.
* 2nd is the text "The Continuous Delivery Company"
* 3rd is the menu
* 4th is a black bar which works as a separator or ruler to the main part of the page

![image](https://cloud.githubusercontent.com/assets/155492/10677399/69b69dd0-790c-11e5-94f8-957970dd5a06.png)

The nav bar (3rd tier) should collapse in responsive design

**Comment by lakruzz** [comment]
Ivan has a mockup

![image](https://cloud.githubusercontent.com/assets/155492/10690494/984cd350-7982-11e5-9ee6-e6704a68019b.png)

**Comment by lakruzz** [comment]
Looks better - I still thing that the sub pictures should be slightly smaller

**Comment by lakruzz** [comment]
The ribbons must still be an overlay in the pircture

**Comment by illus0r** [comment]
How to split this to "make header on mobile" and "make header on desktop"?

**Comment by illus0r** [comment]
Main banner will be improved in #14
Now header looks like
![image](https://cloud.githubusercontent.com/assets/797993/10756054/9b1d18b4-7cb2-11e5-9771-adaf0da18623.png)
