### ISSUE TITLE
Create site map for the new site

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#102]

**Comment by lakruzz** [comment]
found https://www.xml-sitemaps.com
 which generated:
[new.praqma.com-urllist.txt](https://github.com/Praqma/praqma.github.io/files/83037/new.praqma.com-urllist.txt)

**Comment by lakruzz** [comment]
- [ ] / | /index.html
  - [ ] /services/
    - [ ] /services/consulting/
    - [ ] /services/assessments/
    - [ ] /services/josra/
    - [ ] /services/tool-specialists/
    - [ ] /services/code-conf/
    - [ ] /services/sla/
  - [ ] /training/
    - [ ] /training/docker-admin-ops/
    - [ ] /training/docker-intro/
    - [ ] /training/git-bootcamp/
    - [ ] /training/git-mastering/
    - [ ] /training/jenkins-code/
    - [ ] /training/jenkins-plugins/
    - [ ] /training/jira-admin/
  - [ ] /blog/
    - [ ] /blog/tag/newest/
    - [ ] /blog/tag/jenkins/
    - [ ] /blog/tag/markdown/
    - [ ] /blog/employees/
    - [ ] /blog/linkckecker-jekyll-flavor/
    - [ ] /blog/Pretested-Integration-with-builddsl/
    - [ ] /blog/GiJeLi-tool-stack-howto/
    - [ ] /blog/linkchecker-dockerized/
    - [ ] /blog/test-post-by-bue/
    - [ ] /blog/praqma-gijeli-knowledgebase-presentation/
  - [ ] /about/
    - [ ] /about/customers/
    - [ ] /about/jobs/
    - [ ] /about/offices/
    - [ ] /about/partners/

**Comment by illus0r** [comment]
Now that

  - [ ] /blog/
    - [ ] /blog/tag/newest/
    - [ ] /blog/tag/jenkins/
    - [ ] /blog/tag/markdown/
    - [ ] /blog/employees/

Should be changed with something like 

  - [ ] /blog/
    - [ ] /blog/#Newest
    - [ ] /blog/#Jenkins
    - [ ] /blog/#Markdown
    - [ ] /blog/#Employees

and so on
