### ISSUE TITLE
Create a collection for the jobs listings

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/praqma.github.io#103]
We need a collection page for the jobs listings in the about page.  It should be a sub collection in the about.

---

Complementing @meekrosoft:

@illus0r, Mike already added a handful of job postings that we want on our web. But we still only want the four original about_us pages, so we need to come up with a way of organizing these job postings under jobs.

Maybe we can publish the in the blog format, and simply tag them with `job` and then make the job page one that basically lists blogs with that tag?

...I think that might actually work.

Or we will have to make a jobs collection nested underneath the about_us collection - I need you feed back on how that could be implemented.

The third alternative might be that the job page simply is constructed by a concatenation of the about_us pages.

**Comment by lakruzz** [comment]
I'm marking this as a briefing, lets decide on an approach and then spawn cases off from this one.

**Comment by illus0r** [comment]
Reorganizing your job posts is definitely a good idea :) I like first two approaches: referring to blog posts and adding new collection. First one looks nicer to me.

## Linking to job blog posts
cons:

* we may want to reproduce the look of blog index on `/about/jobs/`, it'll cause code duplication. But I can make a simple mockup - just text links to posts, that'll be the simplest solution.

## Adding new collection
cons:

* that will be the first place with 3 level deep navigation `main menu → about menu → job menu`.

## About pages concatenation
cons:

* pure usability, it's hard to find out do I mach your vacancy or not. Need to scroll much.

**Comment by illus0r** [comment]
@lakruzz can I start withing this task? Size is `medium`

**Comment by lakruzz** [comment]
I'm ok with both 1 and 2. I know @meekrosoft is in favor of 2. So let's give the man what he wants!

Make a three level deep nested collection!

**Comment by illus0r** [comment]
@lakruzz oops, I've accidentally implemented first solution before your comment. You can have a look at http://new.praqma.com/about/jobs/
Second solution seamed less usable to me.

But I still can redo the task with another

**Comment by lakruzz** [comment]
@illus0r @meekrosoft Good enoug for MVP, But probably not for going forward.

Let's leave it for now - Mike, are you OK with that?

**Comment by meekrosoft** [comment]
Yup, perfect is the enemy of done!
