### ISSUE TITLE
Automate the change of email signatures

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/praqma.github.io#11]
As far as I can see, Gmail provides an API to change the email footer of all the employees of praqma.
Shouldn't we automate this instead of asking 42 people to spend 5 min. each time?
https://support.google.com/a/answer/175187?hl=en&ref_topic=29816

**Comment by lakruzz** [comment]
More specifically the [`sendAs`](https://developers.google.com/gmail/api/v1/reference/users/settings/sendAs) resource

**Comment by lakruzz** [comment]
@sofusalbertsen good input!

**Comment by kryptag** [comment]
@lakruzz how should we do this, will we all use the same signature at the same time or should people still be able to pick and choose. Because if we all use the same signature in the sense of the same banner, i dont see this being hard to implement.

**Comment by sofusalbertsen** [comment]
There are three ways to do it:

### All get the same banner
Easy, no config, just push a button and go! Then everyone gets the same banner.

### Central list of who-gets-what banner.
We sometimes have two events simultaneously in two different countries. Therefore needing different banners.

### Opt-in/out through list
The icing on the cake; let people decide if they want it automated or not by putting them in a file in a GH repo.

So what would we want?

**Comment by lakruzz** [comment]
People still need individual mail signatures - And different Banner adds

**Comment by sofusalbertsen** [comment]
so the only thing needed to be chosen is if they should be able to opt out of the automatic banner update cycle?

**Comment by lakruzz** [comment]
Closing this one here - and continuing in Praqma/mailsignature#4 - we follow the code (which was relocated)
