### ISSUE TITLE
Finish frontpage of new.praqma

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.github.io#118]
- [ ] Decide on the four stories that shall be on the cover
- [ ] Find suitable pics for each

Front page is controlled by the content of:
https://github.com/Praqma/praqma.github.io/blob/master/_data/front.yml

**Comment by lakruzz** [comment]
This now seems to be the show stopper, apart from the front page, we're pretty much ready to go live - let's have a dialog about this one:

W need 4 stories to put on the front - any suggestions?

@meekrosoft @monaslarsen

**Comment by lakruzz** [comment]
@monaslarsen 

Mona can you fill in a bit of update on this issue?

- [ ] Have you chosen 4 stories?
- [ ] Have you chosen the pic's to match it?

What's the status?

**Comment by monaslarsen** [comment]
Hey @lakruzz 

I have chosen the content I find relevant, added images and adjacent links.

I would like some help tomorrow on how to tame ribbon sizes and image sizes
