### ISSUE TITLE
Use folders rather than files for menu items

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#12]
Regarding 650faf1

I'd like the menu items to represent folders rather than files.

So instead of having _Training_ pointing to `/training.html` it should point to `/training/`and then the content should be put in an `index.md` file in that folder.

(as per the implementation of www.josra.org and www.code-conf.com etc.)

**Comment by illus0r** [comment]
@lakruzz Sure, I can make it. But I'd like to understand what for?
I considered moving all the page files to one dir like `pages` to keep root folder clean.

**Comment by lakruzz** [comment]
In the static HTML structure generated by Jekyll the path to the file becomes part of the final URL.

So take for instance a set of training related pages like the _index_, a _git course_ and a _jenkins course_ would have the following urls:

    /pages/training.html
    /pages/git-course.html
    /pages/jenkins-course.html

Where as in my approach the same URLs will be

    /training/
    /training/git-course.html
    /training/jenkins-course.html

**Comment by illus0r** [comment]
@lakruzz, I've got your idea, now it has a sense for me. We could go even further and group pages like this:
```
/pages/training/index.html
/pages/training/git-course.html
/pages/training/jenkins-course.html
/pages/something-else/index.html
/pages/something-else/some-page.html
```
so all pages are in one dir in on the root but still well structured.
I see, you want to add a submenus in the future. Suggested approach will help us to generate submenus on the basis of folder nesting (instead of nav.yml)

What approach would you like more?

**Comment by lakruzz** [comment]
No thanks.

`pages` in this context it pretty redundant - it's a web site!  ...everything (from an end-user's perspective) is _pages_.

There wouldn't be one single page that I could show that _wouldn't_ be in `pages`  ... that's redundancy by definition :-)

If the only thing we gain from that is that the root seems more tidy, it's a far to high price to pay for ugly URLs - since we're the only ones looking at the git repo.

**Comment by illus0r** [comment]
@lakruzz how could you think so weird thinks about me? :)
I didn't intend to make ugly urls.
You can place files wherever you want and set their urls by frontmatter.

file `/pages/training.html` with frontmatter
```
---
title: Training
permalink: /training/
nav-weight: 20
---
```
will be available on `http://new.praqma.com/training/` only.

**Comment by lakruzz** [comment]
@illus0r I'm so sorry!
I'm flat on the floor - I've got nothing to say:

Honestly I've never used permalink for anything except in the `_config.yml`where I usually set:

    permalink: none

because I don't want the dates to be part of the URL in posts. But the way you use it is smart - thanks for being smarter than me.

AND i discovered myself that using categories in in the front matter solves the same problem for all _non-index.html_ files.

So a file named `2015-10-27-an-interesting-blog.md` with a front matter like:

    ---
    layout: post
    title:  "Welcome to Jekyll!"
    categories: blog 
    ---

and a '_config.yml`with

    permalink:none

will cause the file to be located at `http://new.praqma.com/blog/an-interesting-blog.html` (provided that the file is in a folder named `_posts`.

I'm happy!

lets go with your suggestion:

    /pages/training/index.html
    /pages/training/git-course.html
    /pages/training/jenkins-course.html
    /pages/something-else/index.html
    /pages/something-else/some-page.html

Hope you don't find me too stubborn :-)

**Comment by illus0r** [comment]
@lakruzz Oh, I enjoy working with you :)
I didn't know about categories, thanks, we will use them for blog.

вт, 27 окт. 2015, 22:15, Lars Kruse <notifications@github.com>:

**Comment by lakruzz** [comment]
@illus0r 
I'll close this issue - it's more a strategy for going forward than it is an actual issue - glad we had the discussion though - I Learned something.
