### ISSUE TITLE
Menu is not updating

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#121]
The Home menu item stays active even when I click on another page:

![image](https://cloud.githubusercontent.com/assets/155492/12329150/35b8561c-badf-11e5-907b-75b75fa4d79f.png)

![image](https://cloud.githubusercontent.com/assets/155492/12329162/3ca2cf70-badf-11e5-88de-26ae21b43f78.png)

Only when i go to a sub page (e.g. /stories/employees/) is it corret updated:

![image](https://cloud.githubusercontent.com/assets/155492/12329188/5fcca78c-badf-11e5-8937-75a0394a232d.png)

**Comment by illus0r** [comment]
@lakruzz wow! Looks funny on screenshots. But I didn't manage to reproduce it on http://new.praqma.com/

**Comment by lakruzz** [comment]
Me neither - actually!

But running locally ...hmmm?

**Comment by lakruzz** [comment]
Cant reproduce!
