### ISSUE TITLE
Move the Jenkinsfavs story to the new web

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#123]
take this one http://www.praqma.com/stories/jenkins-favs to a post in the `_posts` dir

make sure to add a redirect in the front-matter:

```
redirect_from: /stories/jenkins-favs/
```

Hmmm or even better - just simply name the markdown `jenkins-favs` ...that should do it :-)

**Comment by praqma-thi** [comment]
Available on http://new.praqma.com/stories/top-jenkins-plugins/
Added Job DSL and Green Balls, dropped Additional Users plugin (topped out at 100 installs).
Organized the plugins on scope (server, pipeline, job) and added an overview with clickable links to make post navigation easier.
