### ISSUE TITLE
'large' images overlap side menu

### ISSUE THREAD

**Issue by praqma-thi** [Praqma/praqma.github.io#125]
### Issue & How to reproduce
Applying `{: .pic .large .center}` to images in blog posts causes them to possibly overlap the side menu.

I pushed a branch called `jenkins-favorites` containing a WIP blog post (stories/top-jenkins-plugins/).
I marked two images with `{: .pic .large .center}`, the larger of the two overlaps with the side menu.

We probably want the size of images in blog posts to be restricted to the text area of the blog post itself.

### Example
![image-stretch](https://cloud.githubusercontent.com/assets/12794699/12395461/0a255d9e-be02-11e5-9ff2-d18dd2c0ce56.png)

**Comment by illus0r** [comment]
Similar things happens on ​*traning pages*​ on mobile, I will fix as well
