### ISSUE TITLE
Make the old Drupal site reply on was.www.praqma.com 

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#126]
I have made the DNS CNAME setting `was.www.praqma.com` -> `gateway.praqma.com``

Which matches the setting for `www.praqma.com`

But when I browse to http://was.www.praqma.com I get a 404 from the Apache server.

I need to have the Apache server on gateway.praqma.com (and maybe also Drupal itself) accept the header and reply to that request.

Anyone with Apache/Drupal experience know how to accomplish that?

@MadsNielsen Please :-)

**Comment by lakruzz** [comment]
@wolfie

I  added the following to `/etc/apache2/httpd.conf`

```
<VirtualHost *:80>

    ServerName was.www.praqma.com
    DocumentRoot /var/www
    DirectoryIndex index.html

    <Proxy *>
        Order deny,allow
        Allow from all
    </Proxy>

    ProxyPass        / http://10.10.1.51/
    ProxypassReverse / http://10.10.1.51/

</VirtualHost>
```

and restarted the service:

```
sudo service apache2 restart
```

**Comment by wolfie** [comment]
I have a feeling that you didn't mean to mention me here :)

**Comment by lakruzz** [comment]
Hi @wolfie!

_he he_

Wolfie is our server - I used @ in the litterate meaning "at" Wolfie ...

You're dismissed :+1:

**Comment by wolfie** [comment]
:D Thank you. 

Nevertheless, it was nice to meet you @lakruzz , and remember to avoid working too late today. Maybe have mid-week beer, while remembering this funny occurrence!
