### ISSUE TITLE
Validate avatar pics on posts

### ISSUE THREAD

**Issue by buep** [Praqma/praqma.github.io#137]
Original title was: Why a 4x3 image on many stories?

![screenshot from 2016-01-20 18 13 50](https://cloud.githubusercontent.com/assets/1579826/12456774/9df1b2e8-bfa1-11e5-830a-39cb4784dbe5.png)

**Comment by lakruzz** [comment]
MVP!!!

- [ ] Go through - and validate - avatar pics on _all_ posts
