### ISSUE TITLE
Too big picture (the one from Day of Docker)

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/praqma.github.io#138]
<img width="1440" alt="screen shot 2016-01-20 at 18 20 07" src="https://cloud.githubusercontent.com/assets/1671664/12456988/96977a5e-bfa2-11e5-93b5-3c502c42aff4.png">

**Comment by buep** [comment]
See also #135 - maybe someone should write little test checking image size is reasonable upon delivery?

**Comment by Andrey9kin** [comment]
Good point

**Comment by lakruzz** [comment]
Too big picture (the one from Day of Docker) at http://www.praqma.com/services/code-conf/

@Andrey9kin moved the URL out of the title and into either a comment or description. Titles don't get marked up
