### ISSUE TITLE
Why is telefone number a link?

### ISSUE THREAD

**Issue by buep** [Praqma/praqma.github.io#142]
![screenshot from 2016-01-20 19 41 22](https://cloud.githubusercontent.com/assets/1579826/12459213/d5552e2a-bfad-11e5-9c4c-786967294ed9.png)

Failing to click it of course...

![screenshot from 2016-01-20 19 38 17](https://cloud.githubusercontent.com/assets/1579826/12459221/de5e62e8-bfad-11e5-9515-5c841a78870e.png)

**Comment by lakruzz** [comment]
@buep 
If you're on a device that can make calls (a smart phone, or if you've registered Skype or something similar to make outgoing calls)  then the link protocol `tel:` will ...make the call :+1:
