### ISSUE TITLE
Stories: Tag filter menu causes awkward resizing

### ISSUE THREAD

**Issue by praqma-thi** [Praqma/praqma.github.io#147]
When resizing the window, the tag filter menu sometimes behaves rather weird and takes up a lot of space.
See below for an example.

Firefox 43.0 (Linux)

![resize](https://cloud.githubusercontent.com/assets/12794699/12474228/c68739bc-c019-11e5-8a33-29fa8b0feeb6.png)

**Comment by monaslarsen** [comment]
Can you solve this without further instructions  @illus0r?

**Comment by illus0r** [comment]
Sure!
