### ISSUE TITLE
Responsive design problem for Iphone

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/praqma.github.io#151]
There are some issues with responsiveness when accessing the page from Iphone - the main pic covers some of the text as shown below.

![img_3727](https://cloud.githubusercontent.com/assets/8004259/12477433/cda40534-c02f-11e5-832b-70bbf51ace81.PNG)

**Comment by monaslarsen** [comment]
@illus0r, can you make the black banner fit inside the image in responsive design?

If not, can you let me know what the limitation are for the text I write in it?

**Comment by lakruzz** [comment]
We already discussed this problem in slack: https://praqmacollaborator.slack.com/archives/web/p1453282379000002

But maybe the solution is also partly in content: The title can not span 3 lines - only two...

But we still need a bit of adjustment I think

**Comment by lakruzz** [comment]
Work #153 before this one!

**Comment by illus0r** [comment]
@lakruzz Hey, I can make font smaller if there are more than one `<br>` in the ribbon text
