### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#16]
Here's a mail I got from @SmadarMHansen  - also not quite in order:

![image](https://cloud.githubusercontent.com/assets/155492/26825557/d360db02-4ab5-11e7-8ecc-9d1ce1444de3.png)

**Comment by kryptag** [comment]
@lakruzz i need information from where this is used, because it works flawless on gmail and hotmail

**Comment by DharaniSP** [comment]
Smadar, can you please send a mail with your new email signature to me and
florent?

We need to see if something needs to be fixed.

/Lars

**Comment by sofusalbertsen** [comment]
@kryptag I had the same issue, removed the line breaks in mine manually and then it works :)

**Comment by lakruzz** [comment]
closing as duplicate (continues) in Praqma/mailsignature#2
