### ISSUE TITLE
Header - small corrections

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#16]
The banner should have some padding at the top - we need some air between the loge and the top of the page:

The black bar should be slightly closer to the menu and there should be padding in the bottom to the main content.

![image](https://cloud.githubusercontent.com/assets/155492/10739347/2a005484-7c1c-11e5-8213-887391b47cef.png)

Closer to whats in the [off-set document in google drive]( https://docs.google.com/document/d/1Zo5QKt5t2_gRc9pxQnReSWDuJVfF8jwrmNuglf5Yqe8)

**Comment by illus0r** [comment]
Dear, @lakruzz, I've promised to align all elements according to your mockup and I'm going to keep my promise :-) In fact It's already fixed on that cunning af9f7f2 revision

**Comment by lakruzz** [comment]
Sorry - I'm just being impatient ;-) no worries

**Comment by illus0r** [comment]
Now like on the picture (on local repo)

![image](https://cloud.githubusercontent.com/assets/797993/10756054/9b1d18b4-7cb2-11e5-9771-adaf0da18623.png)
