### ISSUE TITLE
Make sure the praqma logo don't need to be resized

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#18]
This is the reply I sometimes get from people where I used the new signature

![image](https://user-images.githubusercontent.com/155492/27282689-48d52812-54f1-11e7-83fe-b3e446f28d01.png)

The Praqma loge, must be downsized - the to size it _need_ to have - not bigger

**Comment by lakruzz** [comment]
@kryptag  - one for you...

**Comment by kryptag** [comment]
the new image is 160 pixels wide, so there is no css in there.

**Comment by lakruzz** [comment]
Closing this one and continues in Praqma/mailsignature#3 (the code base moved)
