### ISSUE TITLE
Blog subpage design

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#19]
![praqmaweb_blog](https://cloud.githubusercontent.com/assets/155492/10782485/09df3e78-7d51-11e5-964b-c55d7c255511.jpg)

Here's our graphical designer's mockup for the blog posts.

- [ ] It should be divided in 3/4 for the blog and 1/4 for a right hand sidebar
- [ ] The sidebar should have a Call-to-action signup on the newsletter in the top
- [ ] In the sidebar below the newsletter signup there should be a blog content selector (more on this on a separate issue)
- [ ] Should add tag references to this page

the front matter of a post should look something like this:

    ---
    layout: post
    title: GiJeLi setup
    tags: [Featured, Gijeli, Wiki, MarkDown, Ruby]
    avatar: /images/the-avatar-for-this-post.png
    author: Lars Kruse
    categories: blog
    ---

The post is a post even in the Jekyll context, which meant that it shall reside in a folder named `_posts` (I'm thinking `/pages/_posts/*`) and the file name shall follow the following naming convention.

    YYYY-MM-DD-the-name-of-the-post-all-lowercase.md

The caption that is shown on the Blogs index (#22) comes from the class `caption` in the individual blog posts. In other words the MarkDown for is expected to contain something like this:

    _Jekyll is a Ruby gem that renders MarkDown and Liquid to static html pages. 
    Jekyll is the stand-alone engine that drives GitHub pages. By installing Jekyll 
    you can effectively have an equivalent to GitHub pages anywhere._{: .caption}

**Comment by illus0r** [comment]
@lakruzz one thing confuses me.
Usually color is a usability tool: we code similar  elements with a similar colors. Now I can not understand the meaning of orange color on provided mockups: sometimes orange is a link, in other cases orange is a bage (like data), sometimes is a webform placeholder, sometimes just a text.

I remember your words about my interfering into design, so I'll implement current mockups. Then, if you wish, I will suppose some corrections.

**Comment by illus0r** [comment]
@lakruzz is this orange text a blockquote?
![image](https://cloud.githubusercontent.com/assets/797993/10792125/79591bc0-7d9c-11e5-9c23-eeeaad50e221.png)

**Comment by lakruzz** [comment]
I think that you are right that there is a bit of confusion in this area. 

I'll have a chat with our graphical designer. I'm thinking that I'd like to use the orange test for headers, rubrics, label captions etc and then the links will have to be - _something else_ ...with out exactly knowing what exactly that is.

On http://www.code-conf.com/cph15/program/ we're using orange text for links
On http://www.josra.org/blog/to-branch-or-not-to-branch.html we use a blue one with a shadow effect on a:hover.

I'd like to hear your feed-back

**Comment by lakruzz** [comment]
>is this orange text a blockquote?

Nope - it's just a graphical effect - adding orange effect - eye candy!

**Comment by illus0r** [comment]
@lakruzz we'd beter keep in mind, github can not resize pictures. We have two ways:

* make two copies (by hand or automatically) and include two images to frontmatter (or include one and alter url via the liquid)
* let it be. Use the same big image for blog index. The loading time will expand.

**Comment by lakruzz** [comment]
Let's go with 

>let it be. Use the same big image for blog index. The loading time will expand.

for now!

**Comment by lakruzz** [comment]
@illus0r I've changed this issue form Size - too big and Prio 1 to simply having a label named "briefing"  as it appears that we're not actually working on this issue but use it to brief and discuss issues and then to spawn other smaller cases off from it.

This is a good approach, I just don't want it to sit in our milestone and give the impression that we still have a lot of work to do here - when we're actually close to wrapping it up.

**Comment by illus0r** [comment]
@lakruzz what a relief! Thanks for that

вт, 3 нояб. 2015, 13:16, Lars Kruse <notifications@github.com>:
