### ISSUE TITLE
Proofreading on customarcases

### ISSUE THREAD

**Issue by adamhenriques** [Praqma/praqma.github.io#2]
Some of the case stories need proof reading fx. http://www.praqma.com/stories/grundfos-case/ has "#" some places in the text.

**Comment by lakruzz** [comment]
Hej mester.

Er du godt opmærksom på, at du ikke skal ind i praqma/praqma.github.io mere
- den er omdøbt til Praqma/praqma.com.

[image: ____________________________________________________________]
Lars Kruse M.Sc.
Partner & Co-founder
lak@praqma.net
+45 20 87 25 30 <+45%2020%2087%2025%2030>
Skype: lakruzz
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
http://www.code-conf.com/?src=mailbanner16

**Comment by adamhenriques** [comment]
Yes, så det godt og slettede lige efter, beklager.

[image: ____________________________________________________________]
Adam Henriques
Sales & Marketing
ah@praqma.net
+45 28 12 90 94 <+45%2028%2012%2090%2094>
Skype: adamhenriques
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
http://www.code-conf.com?src=mailbanner16
