### ISSUE TITLE
Set the fonts

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#2]
We need to decide on a font, Our graphical designer suggested:

Headers: Roboto Condensed
Body text: Roboto

Text in ribbons: Ubuntu Condensed
 (e.g. as overlay on the main picture on the landing page)

__fonts are available on google__

**Comment by illus0r** [comment]
Hey, issue #2, why are you not closed yet? I fixed you!

**Comment by illus0r** [comment]
Hey, @lakruzz! How to close the issue?

**Comment by lakruzz** [comment]
@illus0r you are doing the right thing - it automatically gets closed when it is merged into the default branch (`master`).

So we just want you to work on master - don't we :-)

It's fixed lets go through it on the hangout later today
