### ISSUE TITLE
Training courses - subpage design

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#20]
![praqmaweb-training](https://cloud.githubusercontent.com/assets/155492/10782826/bfe5b376-7d53-11e5-906b-0e607903ee89.jpg)

This is the page shown for a training course e.g.  `http://www.praqma.com/training/jira-admin.html`

- [ ] It shall be divided in 1/4 for a course menu 2/4 for content and 1/4 for a "fact-box panel"
- [ ] The course menu shall show all the trainings available (all pages in `/training/*`) (more on this on a separate issue)
- [ ] The factbox (right sidebar) shall be fed from properties in the front matter for the individual page
  * Duration
  * Level
  * Recommendation
  * Hands-on
  * Location

**Comment by illus0r** [comment]
@lakruzz hey, I'll need a mobile mockups for all new pages. It's easier to add than subtract.
If you wish, I can make them according to a corresponding task.

**Comment by lakruzz** [comment]
Please feel free to create the mobile pages according to what you find being best practice.

When we go to smaller sized screens it's typically all the fancy graphics that's being thrown over board anyway.

The mobile pages I trust that you can do equally as good as our graphical designer.

Give it your best shot - and let me know when you have something ready and I'll give you some feed-back on the direction. 

Is that an OK approach for you?

**Comment by illus0r** [comment]
@lakruzz yep! We can work this way.

**Comment by lakruzz** [comment]
@illus0r 

In relation to #37 I've added two files in `pages/training/*` I want you to use them instead of the ones you are currently using in `_training`

**Comment by illus0r** [comment]
@lakruzz made #39 after your comment

**Comment by illus0r** [comment]
@lakruzz 
- what happens after I click `Register`?
- what does symbol `E` on the buttons mean?

**Comment by lakruzz** [comment]
You should'n consider that - it's part og the content (MarkDown) on the individual page :-)

**Comment by lakruzz** [comment]
![image](https://cloud.githubusercontent.com/assets/155492/11028148/3021b0f6-86bc-11e5-9fe4-892dfaaeba63.png)
The font in the right sidebar should be smaller, and the headings in bold text
