### ISSUE TITLE
Training - index page

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#21]
![praqmaweb-trainingfront](https://cloud.githubusercontent.com/assets/155492/10783857/fb5c107e-7d5a-11e5-8198-b6953c30ecde.jpg)

The training index page has it's own lay-out has the same division as the individual training pages (issue #20)

- [ ] 1/4 for course menu, 2/4 for content 1/4 for right sidebar (there is a separate issue for this)
- [ ] The course menu behaves as on the individual training page
- [ ] The right sidebar is a separate `include`

The front matter of this page will look something like this:

    ---
    layout: training-index
    title: Training
    tags: [Jenkins, Git, Artifactory, Jira]
    permalink: /training/
    ---

**Comment by illus0r** [comment]
@lakruzz what a relationship is between left column (pictures) and middle one (course descriptions)?
I see some of them intersect, though there are more items in left column.

**Comment by illus0r** [comment]
@lakruzz some left column pictures look disabled. Shouldn't we search for a better solution?

**Comment by lakruzz** [comment]
At this point simply focus on 

- [ ] Grab the pictures from all the relevant pages
- [ ] Show them in DIVs that are quadratic in size - two on each row
- [ ] The title of the pages should be underneath each picture
- [ ] Each picture should be a link to the individual page 

The actual content is simply MarkDown, you dont need to address that - just produce a `_layout` called training.

do you understand what I mean?

**Comment by illus0r** [comment]
@lakruzz you mean the content of `/training/` is formed from markdown without liquid. And all pictures should be collected from `site.trainig` collection and titled with corresponding titles.

**Comment by illus0r** [comment]
> The title of the pages should be underneath each picture

Should it look like this?
![praqma-trainings](https://cloud.githubusercontent.com/assets/797993/10995940/b0a8d042-8491-11e5-84db-9017b29f7a44.png)

**Comment by lakruzz** [comment]
Right, but then maybe the picture should still be in a 4:3 format and then use the remainder 4:1 fir the caption, so the total space used is square.

**Comment by illus0r** [comment]
all right

**Comment by illus0r** [comment]
@lakruzz have a look, I've put all training pages together. No styles, content only.

**Comment by illus0r** [comment]
@lakruzz Do we still need this task?
