### ISSUE TITLE
Blogs - index

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#22]
![praqmaweb_blogfront](https://cloud.githubusercontent.com/assets/155492/10784081/4eb6b494-7d5c-11e5-966d-95d92cbb78d7.jpg)

The blog index is the page accessible at `http://www.praqma.com/blog`

- [x] It is divided in 3/4 for content and 1/4 for a right sidebar
- [ ] The right sidebar is the same as on the the individual blogs (#19)
- [x] The index itself is listing all blogs that are tagged `featured` sorted by a weight indication (e.g. `nav-weight`) both the tag and the weight are read form the front matter of the individual blog posts
- [x] The content space is divided in 1/4 for an avatar picture and 2/4 for caption - Both the avatar picture and the caption comes from the individual blog posts (See #19 for details on the front-matter of posts)

## An idea for implementation
We could generate the index at compile time as a complete list of all tags, sorted by 1) tag and 2) date

We could use CGI parameters and a JavaScript hooked up to  `<body onload="...">` to hide all the HTML elements that isn't part of the scope.

Consequently:

    www.praqma.com/blog/?tag=git
    www.praqma.com/blog/?tag=jenkins

Would list all posts that had the tags `git` or `jenkins`respectively. Newest on top.

The default should be the tag `featured` meaning that

    www.praqma.com/blog/
    www.praqma.com/blog/?tag=featured

Produce the exact same output.

The sort order for the `featured` tag should be the date, but rather the 1) nav-weight and 2) date but tis exception should be handled in the liquid script that generates the page to begin with

**Comment by illus0r** [comment]
@lakruzz sure, we can consider another approach instead of JS tag filtering. Like [here](http://christianspecht.de/2014/10/25/separate-pages-per-tag-category-with-jekyll-without-plugins/)

pros: no JS hacking, faster, less unnecessary code on page.
cons: you'll have to make a new empty file for every new tag.

**Comment by lakruzz** [comment]
@illus0r 
The [approach you point to](http://christianspecht.de/2014/10/25/separate-pages-per-tag-category-with-jekyll-without-plugins/) is fine - we can get started this way.

The cons you mention might be something that we might want to automated at a point, but for now i'm OK with this approach.

IN the snippet snown


    {% for post in site.tags[page.tag] %}
      <li>
        {{ post.date | date: "%B %d, %Y" }}: <a href="{{ post.url }}">{{ post.title }}</a>
      </li>
    {% endfor %}

We can easily access `page.avatar` 

I'm not sure that we can easily access the `.caption` class in the document itself - but I'm OK with actually adding a page.caption property for now...

**Comment by illus0r** [comment]
@lakruzz how much `.caption`s may we have on page?

**Comment by lakruzz** [comment]
Actually we would need _as much_ as required to make it look good in the Lay-Out.

There is roughly 60-65 chars in each line and we need somewhere between 2 1/2 and 4 lines to look good so I'd say: 

__At least the size of a tweet (140 chars) but no more than 2 tweets (280 chars)__

**Comment by illus0r** [comment]
@lakruzz can I make a label **In progress** or like this?

**Comment by lakruzz** [comment]
You mean a label in the GitHub issue system, to indicate which one your working on?
Fine!

Good idea! I made a white "[Work In Progress](https://github.com/Praqma/praqma.github.io/labels/Work%20In%20Progress)" label!

**Comment by illus0r** [comment]
@lakruzz I like it!
Current milestone is flooded by a plenty of tasks and subtasks. I'll create even more of them. Can we dedicate a separate milestone for a blog?

**Comment by lakruzz** [comment]
Right - I created a milestone "[Blog related](https://github.com/Praqma/praqma.github.io/milestones/Blog%20related)" 

But most of the stuff was moved there anyway :-)

But I like it - lets work with the blogs first!

**Comment by illus0r** [comment]
@lakruzz here we go!
How much blog posts will we have? Will we use a pager?

**Comment by lakruzz** [comment]
...not for now - we'll take it when it becomes a problem.

**Comment by illus0r** [comment]
@lakruzz I made posts look like this

![image](https://cloud.githubusercontent.com/assets/797993/10904624/d1cc1d1a-8225-11e5-9f19-0859fddd9a91.png)

There is no date on mockup. Should it be?

**Comment by lakruzz** [comment]
The blog post date is fine, thanks.  The format of the icon/avatar is not quite right, you're using a 2:1 format (width:height)  I'd rater want a standard 4:3 format.

Also I'd like this page to be wrapped up soon, Are we challenged by capturing the picture? If so I'm ready to have as a prerequisite, that the blog editor must point to it explicitly as part of the front matter

**Comment by illus0r** [comment]
@lakruzz switched an image format.

> Also I'd like this page to be wrapped up soon

do you mean "this issue will be over soon"?

> Are we challenged by capturing the picture? 
> If so I'm ready to have as a prerequisite, that the blog editor must point to it explicitly as part of the front matter

Did not understand :-)

**Comment by lakruzz** [comment]
Yep! _Wrap up_ = _close_ :+1:

**Comment by lakruzz** [comment]
I was just wondering if, the reason why there aren't any pics on the blog index has to do with the fact that I wanted it to be grabbed from the 1st pic in the content is a challenge - If that's the case, then lets just add the avatar/icon directly in the front matter - then it's easy.

**Comment by illus0r** [comment]
@lakruzz I can take images from this mockup, if you wish. But they are too small for a post page. I'll take custom images from the internet.

**Comment by lakruzz** [comment]
As mentioned in #35 - You're off - I'm on it :+1:

**Comment by illus0r** [comment]
@lakruzz :-)

вт, 3 нояб. 2015, 15:51, Lars Kruse <notifications@github.com>:
