### ISSUE TITLE
The blog search box in the right sidebar

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#23]
![image](https://cloud.githubusercontent.com/assets/155492/10784918/f9b1d406-7d60-11e5-9e77-b19419102ac3.png)

The right sidebar on blog index #22  and blog posts #19 is listing a short list of options and a search field.

This can be implemented as a nav-bar

- [ ] The topmost item is called `newest` and is listing the newest `n` blog posts
- [ ] The remainder of the menu items are just tags used in blog posts - when a tag is clicked, the posts that has the tag are listed - sorted by date
- [ ] The last menu item is a search field for free-text search - currently the search is simply executed as google search on `site:praqma.com`

__Priority__
The _Newest_ and _Search_ fields has lower priority than the tags.

The result shall be showed in a page that has the exact same format as the blog index #22  presented at `http://www.praqma.com/blog`

**Comment by illus0r** [comment]
@lakruzz so you want to mix blogpost names with tags into one hip?

* Network of Traces prototype
* Return of the Memory Map plugin
* Josra charter - Pending Changes
* Josra + Academia
* First tag
* Second tag
* Git
* Fetured
* Another tag

I'd like to distinguish them.

Or you want to make the first item in *the tag list* to be a link to the blog (*newest* is the same, as your *blog front page*)?

* Newest
* First tag
* Second tag
* Git
* Fetured
* Another tag

that makes more sense for me

**Comment by illus0r** [comment]
We need to make one more task for **newest** and close the issue as a duplicate.

**Comment by lakruzz** [comment]
@illus0r 

>Or you want to make the first item in the tag list to be a link to the blog (newest is the same, as your blog front page)?
>
>Newest
>First tag
>Second tag
>Git
>Fetured
>Another tag
>
>that makes more sense for me


Yep, like this - definitely

**Comment by illus0r** [comment]
Decomposed into #25 and #24
