### ISSUE TITLE
Show blog post tags on the right sidebar

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#24]
Task as a part of #23 

![image](https://cloud.githubusercontent.com/assets/155492/10784918/f9b1d406-7d60-11e5-9e77-b19419102ac3.png)

The right sidebar on blog index #22  and blog posts #19 is listing a short list of options and a search field.

This can be implemented as a nav-bar

just tags used in blog posts - when a tag is clicked, the posts that has the tag are listed - sorted by date

**Comment by illus0r** [comment]
@lakruzz Just to check if I got it right:

* **Newest** — all blog posts. I can get there by sidebar menu only.
* **Featured** — by tag `featured`. Url is `www.praqma.com/blog/`. I can get there by main menu
* **GIT** — by tag `GIT`. Url is `www.praqma.com/blog/?tag=git`. I can get there by sidebar tag list or by... I don't see tag references on blog subpages. But we can add if you want.
* Another tags like `GIT`…

**Comment by lakruzz** [comment]
Right! You got it!

True you dont see a tag-list on each individual blog post, but I'm on the same page as you: Of course we need the tags on each individual blog to be listed as part of the layout of #19  - Feel free to add it where you want - and we can run it by our graphical designer later!

**Comment by illus0r** [comment]
I'll make styling in #33
