### ISSUE TITLE
Add a ATOM or RSS feed

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#26]
At some point - we'd like to support an RSS/ATOM feed 

Could be this one https://github.com/jekyll/jekyll-feed

...or something similar - there are plenty out there

**Comment by illus0r** [comment]
Should **all** posts go to RSS or just featured?

**Comment by lakruzz** [comment]
All posts - but don't start on this one - It's on the backlog, it's not important and actually, we would probably rather have people signing up for our news letter than subscribing to RSS feeds (We want to know who they are - people can subscribe to feeds anonymously)

**Comment by illus0r** [comment]
@lakruzz implemented the simplest RSS feed without the atom plugin. I use **[Feedly](http://feedly.com/)** to read my feeds, so Praqma looks like
![image](https://cloud.githubusercontent.com/assets/797993/11145988/69e0dd14-8a1b-11e5-9e58-c6bbaeb8513a.png)

**Comment by lakruzz** [comment]
HI Ivan

How does this work - what's the commit that implemented this?

**Comment by illus0r** [comment]
@lakruzz [this one](https://github.com/Praqma/praqma.github.io/commit/556fe129a5002bd9cd74e155692e2464f020cebc)

**Comment by illus0r** [comment]
```
<link rel="alternate" type="application/rss+xml" title="Subscribe via RSS" href="/feed.xml" />
```
This line tells to a rss reader, what to read.
