### ISSUE TITLE
Make rough blog index page

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#27]
![praqmaweb_blogfront](https://cloud.githubusercontent.com/assets/155492/10784081/4eb6b494-7d5c-11e5-966d-95d92cbb78d7.jpg)

subtask of #22

Just show all necessary data from sample blog posts, with no design.

**Comment by lakruzz** [comment]
@illus0r 
Feel free to copy the content from the [Josra blog](https://github.com/josra/josra.github.io/tree/master/blog/_posts) to this repo and play with it (hack it as much as you want)  - so you have some volume to work with.

**Comment by illus0r** [comment]
@lakruzz yeah, just wanted to ask for this info) Thanks
