### ISSUE TITLE
Add a newsletter subscription form

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#29]
![image](https://cloud.githubusercontent.com/assets/797993/10792736/0a7cd14e-7d9f-11e5-9cfb-06005b86bf73.png)

subtask of #22 
Should be on blog index and post pages.

I'm going to use formspree.io to receive submitted forms by email. If you like it.

**Comment by illus0r** [comment]
@lakruzz I set a milestone for a subtask, if I create it after a task with a corresponding milestone set by you. Now you didn't ask for this feature explicitly.

**Comment by lakruzz** [comment]
Actually we're using Mailchimp.

The naked (bare minimum) embedded HTML I generated from mailchimp looks like this


    
    <div id="mc_embed_signup">
    <form action="//praqma.us5.list-manage.com/subscribe/post?u=4cd7193551aaee65c6da509a1&amp;id=24ac966787" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
        <div id="mc_embed_signup_scroll">
    	
    <div class="mc-field-group">
	    <label for="mce-EMAIL">Email Address </label>
	    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
    </div>
    <div class="mc-field-group">
	    <label for="mce-FNAME">First Name </label>
	    <input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
    </div>
	    <div id="mce-responses" class="clear">
		    <div class="response" id="mce-error-response" style="display:none"></div>
	    	<div class="response" id="mce-success-response" style="display:none"></div>
	    </div>    
        <div style="position: absolute; left: -5000px;"><input type="text" name="b_4cd7193551aaee65c6da509a1_24ac966787" tabindex="-1" value=""></div>
        <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
        </div>
    </form>
    </div>
    
    

You can take off-set in that and then style it according to Tenna's mock-up

 (Btw: Tenna is the name of our graphical designer)

**Comment by lakruzz** [comment]
> I set a milestone for a subtask, if I create it after a task with a corresponding milestone set by you. Now you didn't ask for this feature explicitly.

:+1: 
...works for me - I'll pull the brake if i disagree.

**Comment by illus0r** [comment]
> ...works for me - I'll pull the brake if i disagree.

arrr, didn't understand :(

**Comment by lakruzz** [comment]
* When you create a sub task off another, you will assign it to the same _milestone_ and give it the same _priority_
* If either milestone og priority needs to be changed - I'll do it ...no worries!

**Comment by illus0r** [comment]
@lakruzz got it

**Comment by lakruzz** [comment]
@illus0r I'v bumped the prio on this one from should have to _must have_.

**Comment by illus0r** [comment]
@lakruzz great. I like **must have** :)

**Comment by illus0r** [comment]
@lakruzz I changed text a bit to make it consistent: the same names for the same things. I'd like to go futher: now a site visitor can only guess what he is subscribing for. I believe, a slight text change can improve conversion.  So, could you clarify: why this subscription is useful for a visitor?

**Comment by illus0r** [comment]
@lakruzz and good time to think, how search and newsletter blocks should be arranged on mobile. Now they are above other content.

![image](https://cloud.githubusercontent.com/assets/797993/10938387/d1d3c78c-830a-11e5-8d39-d2dcd1d00822.png)

**Comment by lakruzz** [comment]
Great - Looks fine for now, let's move on to next issue.

@illus0r  i closing this one with 1bf18f5 ...which is included in 9fd5895
