### ISSUE TITLE
Ribbon overlays on full-width (main) picture

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#3]
![image](https://cloud.githubusercontent.com/assets/155492/10678308/cdaabb0a-7911-11e5-9f2a-90231a3484c9.png)

The idea behind the ribbons in the toprow is that the text in the picture isn’t part of the picture, but rather something that’s applied by the content editors as code.

Kind of like how we implemented the banner on www.code-conf.com/jues15 (source) except that we want the input as the YAML exemplified above, not DIVs in HTML.

The caption in the big picture should appear when the mouse hovers over the picture, something like this:

![image](https://cloud.githubusercontent.com/assets/155492/10678341/0d6e32e4-7912-11e5-98e6-720396825627.png)

**Comment by illus0r** [comment]
made everything excepting #14
