### ISSUE TITLE
Implement new header design for a widescreen

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#30]
![image](https://cloud.githubusercontent.com/assets/797993/10793202/d76205fc-7da0-11e5-9c00-08cb06903f54.png)

Without social buttons, they are for #4

**Comment by lakruzz** [comment]
I've thrown this to the backlog.

Let's not spend time on this right now

**Comment by lakruzz** [comment]
Let's go with this one next - I want this new header instead :+1:

**Comment by illus0r** [comment]
@lakruzz woohoo! I'll do it tomorrow

**Comment by lakruzz** [comment]
The "Case Stories" menu should be taken out - we're not going to use it in the MVP

**Comment by illus0r** [comment]
done and delivered
