### ISSUE TITLE
Main banner bug on firefox+windows

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#31]
![default](https://cloud.githubusercontent.com/assets/797993/10803304/8bc22406-7dd2-11e5-8ef9-0a7fa4d9b8f8.png)

Extra space between ribbon lines

**Comment by lakruzz** [comment]
Currently the ribbon over the big picture is more like a box - than it is a ribbon:

![image](https://cloud.githubusercontent.com/assets/155492/10905217/0bb936d2-8219-11e5-889a-143b753be415.png)

I would like it to be as on the original mockup:

![image](https://cloud.githubusercontent.com/assets/155492/10905263/4fd1903a-8219-11e5-89dd-c92e7cee4bbb.png)

So that the colored background follows the text

**Comment by illus0r** [comment]
@lakruzz I struggled a lot with this ribbon. Tried three different methods,
and decided to get back later.
How to manage such situations in the future? Should I make tasks for such
bugs?

вт, 3 нояб. 2015, 12:55, Lars Kruse <notifications@github.com>:

**Comment by lakruzz** [comment]
@illus0r Be sure to notify me when something like that is taking more time than anticipated - I'll help you prioritize:

1) Either I really, really want it, and we will schedule more time for the task

or

2) We can discuss a simpler alternative solution that can be implemented within our original estimate.

**Comment by lakruzz** [comment]
@illus0r sorry for the mess - should only have been one commit.  Anyway I solved it by a bit of a hack, but I would rather have that we leave it for now and - we can probably come up with a snippet of liquid code that des the right (same) thing - But I really want to move on.

**Comment by illus0r** [comment]
@lakruzz wow! Use a liquid is a great idea. Tomorrow I'll have a look at your changes in code

**Comment by illus0r** [comment]
@lakruzz I changed a bit your solution: var in `_config` is only one, it's split up into parts by <br> tag.
You'll be able to have a look after jenkins accept my commit

**Comment by illus0r** [comment]
sorry for solving a backlog task, it was really small
