### ISSUE TITLE
Highlight *blog* main-menu link on all all blog related pages

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#32]
![image](https://cloud.githubusercontent.com/assets/797993/10845085/143b4df0-7f16-11e5-8763-72b756b1f664.png)

Should be selected on all tag-pages and post-pages
Now works on `/blog/` only

**Comment by lakruzz** [comment]
@illus0r - This is implemented right? Shouldn't this issue be closed?

(If not then please clarify - then I'm not sure what this issue is about)

**Comment by illus0r** [comment]
@lakruzz yep, just fixed. I need to be more precise in description writing :)
Link `blog` was highlighted when you are on `/blog/` page. But when you are on `/blog/linkchecker-dockerized/`or on `/blog/markdown/` link was inactive. You could only guess, on what page are you.
