### ISSUE TITLE
Style tags and search

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#33]
![image](https://cloud.githubusercontent.com/assets/155492/10784918/f9b1d406-7d60-11e5-9e77-b19419102ac3.png)

**Comment by illus0r** [comment]
@lakruzz I used a google default search box in order to save time. If you need, I can precisely follow a mockup.
Now it looks like this:
![image](https://cloud.githubusercontent.com/assets/797993/10904275/128e3c32-8223-11e5-89b1-c0012e582887.png)

**Comment by illus0r** [comment]
Small bugs
![image](https://cloud.githubusercontent.com/assets/797993/10904437/3315363a-8224-11e5-9e9c-e11477e14e97.png)

![image](https://cloud.githubusercontent.com/assets/797993/10904449/4c30c38c-8224-11e5-989c-cc5b26913437.png)

**Comment by lakruzz** [comment]
@illus0r It's good enough for now - we might come back and change it later

**Comment by illus0r** [comment]
@lakruzz oh, just fixed. 
Another thing: google search not mobile friendly now. We can close the task and make new one, when you need to fix it.
![image](https://cloud.githubusercontent.com/assets/797993/10905030/827f5a8a-8228-11e5-83d2-4dae9ac9f72f.png)

**Comment by lakruzz** [comment]
Right!
