### ISSUE TITLE
Load pitures on blog index page

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#35]
![image](https://cloud.githubusercontent.com/assets/155492/10905780/d7db8348-821c-11e5-84c2-c4b1b195dafe.png)

use picture formater 4:3 and not 2:1 as in the curret state:

![image](https://cloud.githubusercontent.com/assets/155492/10905810/09daadba-821d-11e5-8f89-ef9889291347.png)

**Comment by lakruzz** [comment]
@illus0r You seem to be online, but I cant get hold of you on neither Slack, Google chat or mail - apparently only through mentions on GitHub Issues - can we meet in a chat room - Our Slack channel perhaps?

**Comment by illus0r** [comment]
@lakruzz Which images to use? I can find'em myself on the Internet.

**Comment by lakruzz** [comment]
Right :+1: 
... at this point _any_ picture will do - I just want to see the _mechanics_ working - then I can have some og my colleagues update the pictures to even _look good_ later

**Comment by lakruzz** [comment]
All right - sorry!

I See you are doing it already:

    ---
    title: GiJeLi setup
    tags: [Featured, Gijeli, Wiki, MarkDown, Ruby]
    avatar: /images/blog/placeholder.png
    author: Lars Kruse
   ---

This is Perfect! then _I_ (not _you_!) will go and update the pictures!


I believe we can close this one then?
