### ISSUE TITLE
Social bar

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#4]
![image](https://cloud.githubusercontent.com/assets/797993/10792465/d93452a2-7d9d-11e5-902f-177263b291ed.png)
___

The social bar should stick to the bottom of the page and the icons should be transparent grey.

![image](https://cloud.githubusercontent.com/assets/155492/10678415/66ae9628-7912-11e5-964d-247eac4ac5e3.png)

On mouse hover over the icon selected shall lose its partial transparency, as shown below exemplified by the LinkedIn icon.

![image](https://cloud.githubusercontent.com/assets/155492/10678427/7d46f9d4-7912-11e5-90d8-f9d68e985c65.png)

**Comment by illus0r** [comment]
> The social bar should stick to the bottom of the page
is it obsolete?

**Comment by lakruzz** [comment]
Hmm right!

_maybe_

I'd like not to spend too much time on it right now.  I've moved it to the backlog.  This is one of the things we can add later. 

What do you think? Top or bottom?

**Comment by illus0r** [comment]
@lakruzz it depends on your goals. What's a main purpose of the site?

**Comment by lakruzz** [comment]
I've discussed it with my colleagues, we're back to (almost) the original plan:

- [ ] Use the four icons Twitter, LinkedIn, Mail and Phone
- [ ] Make them stick to the bottom of the page as it resizes In small screens present i just before the footer
- [ ] Use the grey (semi transparent black) color
- [ ] Dont implement the hover=black effect - it's not important.

OK?

**Comment by illus0r** [comment]
@lakruzz 
Searching for a phone or email will be a pain. Why don't we just show them in a text?

**Comment by illus0r** [comment]
What should I do, if I want to copy your phone or email into clipboard?

**Comment by illus0r** [comment]
and, to be sure, are you talking about this place for buttons? I marked it with red :red_circle:
![image](https://cloud.githubusercontent.com/assets/797993/11093299/7f9ae88e-889a-11e5-9c53-24819bb9b2b6.png)

**Comment by lakruzz** [comment]
> and, to be sure, are you talking about this place for buttons? I marked it with red :red_circle:

Yes, It should stick to the buttom (so it's always visible, even when the window is resized`

**Comment by lakruzz** [comment]
> Searching for a phone or email will be a pain. Why don't we just show them in a text?

Good point, go ahead and implement :+1:

**Comment by illus0r** [comment]
This takes more time, than I supposed. Now it looks like
![image](https://cloud.githubusercontent.com/assets/797993/11122123/bf613a06-896a-11e5-92c5-d0bb1cf86ee8.png)
But it interferes with other content...
![image](https://cloud.githubusercontent.com/assets/797993/11122146/e9b834ee-896a-11e5-8931-f72933113594.png)
...until I use white background:
![image](https://cloud.githubusercontent.com/assets/797993/11122169/08aac286-896b-11e5-9804-6d841ac17fbd.png)
But white color interferes with background:
![image](https://cloud.githubusercontent.com/assets/797993/11122178/1be6c246-896b-11e5-971d-c651910c181f.png)

We could try to make background white and prevent footer overlapping using javascript.
On mobile we can remove fixing and just show the widget above the footer.
@lakruzz, what do you think?

**Comment by illus0r** [comment]
Improvised a little bit, made a kind of overlay.
![image](https://cloud.githubusercontent.com/assets/797993/11145157/bd3745b4-8a13-11e5-8733-51dce0a8bb6e.png)

Not so bad on gray as well:
![image](https://cloud.githubusercontent.com/assets/797993/11145172/d8c8d3a6-8a13-11e5-9f29-24e5a032eae3.png)

A font bug on mobile, will fix it after your feedback.
<img src="https://cloud.githubusercontent.com/assets/797993/11145179/f6294c32-8a13-11e5-8b98-6e2c38baea57.png" width="300">

**Comment by lakruzz** [comment]
It looks fine

Let's just get the icons right and then wrap it up
