### ISSUE TITLE
Style a post page

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#40]
![image](https://cloud.githubusercontent.com/assets/797993/10968015/a85d84c2-83cf-11e5-92aa-801657703d20.png)

After task #19

output 
- [x] date
- [x] tags 
- [x] image
- [x] caption {: .caption} 
- [x] orange highlights {: .highlight} 

write styles for everything:
- [x] page title
- [x] date
- [x] tags
- [x] captions {: .caption} 
- [x] orange highlights {: .highlight}

**Comment by lakruzz** [comment]
This is now more related to styling in general, I'm taking it off the blog milestone and putting it on the backlog for now

**Comment by illus0r** [comment]
@lakruzz

![image](https://cloud.githubusercontent.com/assets/797993/11092650/fce38f4e-8895-11e5-9959-05c85ac6d736.png)

**Comment by lakruzz** [comment]
Nice!
