### ISSUE TITLE
Loose the watermark in the custom search field

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#41]
![image](https://cloud.githubusercontent.com/assets/155492/10969784/b5be2d06-83ca-11e5-8aa2-78e33976ff15.png)

I found a suggestion to [how it can be done](http://www.frontlinearts.com/replaceremove-watermark-from-google-custom-search-text-box)

**Comment by illus0r** [comment]
@lakruzz
![image](https://cloud.githubusercontent.com/assets/797993/11063995/4f5691fc-87cb-11e5-8a1f-2e44fcada1f8.png)

**Comment by illus0r** [comment]
Text is an image, it was the fastest solution

**Comment by lakruzz** [comment]
OK
