### ISSUE TITLE
Organize left index in square tiles

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#45]
As described in #21 

![image](https://cloud.githubusercontent.com/assets/797993/11032071/db5cb9f2-86e9-11e5-8056-92d63ae52cc3.png)

Avatars should be 4x3 so avatar+caption were a square.

- [ ] made common styles
- [ ] an active item is highlighted
- [ ] mobile testing

**Comment by lakruzz** [comment]
@illus0r Added a new label type "Up Next" I'll use it to indicate to your what I'd like to see next.
When youstart working on something and put the "work in progress" label on it - you can take my "Up next" label off.

If you are done with an issue, and I haven't put the "Up next" label on any thing then your next issue is: "The case with the highest prioritization and the smallest estimate"

OK

**Comment by illus0r** [comment]
Got it.

**Comment by illus0r** [comment]
@lakruzz 
Delivered. Works on different screen sizes. Links don't look like squares, because I tried to make them readable. But if you with we can spend some time to make them better.
![image](https://cloud.githubusercontent.com/assets/797993/11037107/22776314-870d-11e5-9961-0171f23c4439.png)

**Comment by lakruzz** [comment]
Fine for now, we can revisit the subject when we get som feed-back from my colleagues - I'm closing it!
