### ISSUE TITLE
Styles in right sidebar on training sub pages

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#47]
![image](https://cloud.githubusercontent.com/assets/797993/11032534/60b832a4-86ed-11e5-92d4-ef34aab5c3cd.png)

According to mockup #20

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/11058974/dea27c1e-87a7-11e5-8a9e-c762b46e19e6.png)
