### ISSUE TITLE
Style content on a training page

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#48]
![image](https://cloud.githubusercontent.com/assets/797993/11032339/dd7c775c-86eb-11e5-9db0-3b3bbf486c2e.png)

- [x] subheader
- [x] caption
- [x] *Register* button
- [x] eye candy orange text

**Comment by lakruzz** [comment]
Dont style the register button - we will take this to the backlog

The orange eye-candy text it made with `class="highlight"`

    _Sample highlight text_{: .highlight}

**Comment by lakruzz** [comment]
I'd like to argue that tis is a small - not medium issue - especially not the "register" button is not part of it.   agree?

**Comment by illus0r** [comment]
@lakruzz yep. One more time: small - less than ah hour, medium — 2-3 hours.

**Comment by illus0r** [comment]
right?

**Comment by lakruzz** [comment]
Yep!

[image: ____________________________________________________________]
Lars Kruse M.Sc.
Partner & Co-founder
lak@praqma.net
+45 20 87 25 30 <+45%2020%2087%2025%2030>
Skype: lakruzz
Praqma
www.praqma.com
DK: CPH, Aarhus, Allerod
NO: OSL
SE: STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/day-of-docker-osl15/?src=mailbanner>

**Comment by illus0r** [comment]
Would you like me to estimate without margins?

**Comment by lakruzz** [comment]
Yes - in general a _good_ estimate is a _precise_ estimate.

So estimating someting to 7 hrs, but reporting it as 9, is equally bad as reporting it as 5.  

7 is 7 :-)

If you want to put it down as 9 it's really 9 that's the estimate - not 7 as in 

9 is 9 :+1:

**Comment by illus0r** [comment]
![image](https://cloud.githubusercontent.com/assets/797993/11062611/5b97ff1e-87c1-11e5-9147-e97edfe286ee.png)

**Comment by illus0r** [comment]
@lakruzz Result you'll be able to see on http://new.praqma.com/training/code-jenkins/ after jenkins is up.
