### ISSUE TITLE
Styles on the training index page

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#49]
![image](https://cloud.githubusercontent.com/assets/797993/11032442/9497308a-86ec-11e5-9fe9-4d8c411f51e0.png)

- [x] by Praqma is orange
- [x] dates are orange

**Comment by illus0r** [comment]
@lakruzz I made it look like this.
There is no case with several paragraphs withing one header, so I've made this case in `training.md` and rearranged text blocks by margins to make it look well.

![image](https://cloud.githubusercontent.com/assets/797993/11060915/6a4d31bc-87b4-11e5-8eee-6d71d3c53823.png)

**Comment by lakruzz** [comment]
@illus0r slightly confused about this comment:

> There is no case with several paragraphs withing one header

hmmm normally a header should't span multiple lines/paragraphs

> ...rearranged text blocks by margins

I'm not sure I understand!

I tried to look at `training.md` but I'm not seeing the same version as you display here.  Did you push yet?

**Comment by illus0r** [comment]
@lakruzz Just delivered

oh, I tried to say not
```
<h2>
  <p></p>
  <p></p>
</h2>
```
but
```
<h2></h2>
<p></p>
<p></p>
```

**Comment by lakruzz** [comment]
right!

Still not _quite_ sure what we're talking about: I agree that paragraphs shouldn't be inside a header tag - but was that the case? where?

Also your showing me samples in html, but our content is in markdown so it would look like 

     ## header

    paragraph

    paragraph

which would automatically render to 

    <h2></h2>
    <p></p>
    <p></p>

I see in the markdown you have introduced a class `date``

    September 15 — 20
    {: .date}

But I'm not sure `date` is special, it's just a plain `highlight``

    September 15 — 20
    {: .highlight}

...i imagine.

**Comment by illus0r** [comment]
I'm not sure if the subject is significant, but I wanted to explain difference from the initial mockup. As you can see, I've added margin-bottom for h2 elements to make such semantic units:
```
## Nam id inermis phaedrum vituperata, ut erat vocent vis, sea amet

September 15 — 20
{: .date}

solet definitiones ea. Tincidunt consetetur mea ei, an qui quaeque posidonium. Etiam suavitate percipitur ne sea. Vis in maiorum adolescens, sit te timeam mediocrem. Vix nulla accusata ut, vix ad nihil animal, labores blandit eloquentiam mea eu. Id atqui maluisset his, cum ad postea cetero, ei sed graeco omnium.

posidonium. Etiam suavitate percipitur ne sea. Vis in maiorum adolescens, sit te timeam mediocrem. Vix nulla accusata ut, vix ad nihil animal, labores blandit eloquentiam mea eu. Id atqui maluisset his, cum ad postea cetero, ei sed graeco omnium.

timeam mediocrem. Vix nulla accusata ut, vix ad nihil animal, labores blandit eloquentiam mea eu. Id atqui maluisset his, cum ad postea cetero, ei sed graeco omnium.
```
look solid.

**Comment by lakruzz** [comment]
Ooh!
I didn't catch the we were at that level of detail :-)

It's clearly a matter of opinion and therefore I also foresee that this is the level of detail that we will be discussing internally in Praqma as soon as the Minimum Viable Product is out.

At his point, you're free to make/implement your suggestions, and we will evaluate them later.

**Comment by illus0r** [comment]
Yep! So we go on

**Comment by illus0r** [comment]
@lakruzz should we close it?

**Comment by lakruzz** [comment]
Yep - I'm closing
