### ISSUE TITLE
The tagline is too small

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#51]
![image](https://cloud.githubusercontent.com/assets/155492/11095366/ee61dc88-8894-11e5-94d9-f206af0a2f17.png)

The tagline: _The Continuous delivery Company_ is too small in the header (e.g. www.praqma.com)

**Comment by illus0r** [comment]
Right, that's what I saw in chrome:
![image](https://cloud.githubusercontent.com/assets/797993/11242658/2adcc87e-8e14-11e5-9b66-cb577e5ef360.png)
and firefox:
![image](https://cloud.githubusercontent.com/assets/797993/11242680/565477fe-8e14-11e5-8803-78cc29e33b06.png)
and safari:
![image](https://cloud.githubusercontent.com/assets/797993/11242914/ee13b5ae-8e15-11e5-8572-7626b26ecd6e.png)

Looks like you're on Safari :) I'll try to fix it now

**Comment by illus0r** [comment]
@lakruzz I found myself looking for an answer for a half of an hour. I can test on iPad only, but there's no developer console. I have to install Safari on Linux or Windows first, so I've changed a time estimation.

**Comment by lakruzz** [comment]
Ahh  I wasn't refering to the logo, but to the tagline:

![image](https://cloud.githubusercontent.com/assets/155492/11267296/c8a2f11e-8eaa-11e5-9bd8-eab0f98a9bef.png)

I just want it to be bigger - as per the original mock-up.

I'm actually using chrome myself - never used Safari :green_apple:

**Comment by illus0r** [comment]
@lakruzz please, have a look how it looks like on your macbook. I've aligned it on iPad, more testing needed. Throw me a screenshot if any problems.

**Comment by lakruzz** [comment]
closed with 5ba0e0c :+1:
