### ISSUE TITLE
Size (in general) is too large

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#54]
# 100%
![image](https://cloud.githubusercontent.com/assets/155492/11101551/d0f7dd8c-88b7-11e5-9b54-19dd6f68a422.png)

When the web opens in a default sized browser window att 100% it's hard to read the context

# 75%

![image](https://cloud.githubusercontent.com/assets/155492/11101569/efb82bd2-88b7-11e5-9d42-609fae0872aa.png)

When it's zoomed out to 75% the proportions of the page are closer to my expectations and the original mock up

**Comment by lakruzz** [comment]
This case closes #53 as a duplicate

**Comment by lakruzz** [comment]
@illus0r can you try to take `$container-large-desktop:` in `/_sass/helpers/_variables.scss`down a notch - something closer to 950px - 990px (currently it's 1120px)

And then lets' see how that works.

(I'm taking the liberty to size this as small - although I know it's your job to make the estimates :-) )

**Comment by illus0r** [comment]
@lakruzz you're right! A tiny task. Changed to 960px. I'll push after I understand a cause of constant squashing in git

**Comment by illus0r** [comment]
answered in the #git-flow
