### ISSUE TITLE
The Services index

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#57]
page `/services` should be an index of sub content like the other ones you did (Training and blog)

I'd like it to presented like the smaller pictures on the front page - but in two rows - So it will become

Six subpages (I'll make sure you get sample copy  asap)

But imagine that these pages (like the training and blog pages) have the front matter you expect:

Avatar, index prio, caption etc

And that you will arrange them like the small pictures on the front page

![image](https://cloud.githubusercontent.com/assets/155492/11146711/e38974a6-8a10-11e5-9529-88fd365288d8.png)

Only, you'll have two rows of three each. I'm working on a mockup _ it will be ready for you soon.

**Comment by lakruzz** [comment]
I have closed #58 @illus0r you're good to go

**Comment by lakruzz** [comment]
...And I have a mock-up for you:

![image](https://cloud.githubusercontent.com/assets/155492/11147848/1feb6fb4-8a19-11e5-866b-2d9ebbe8d4fc.png)

**Comment by illus0r** [comment]
@lakruzz 
1. pictures in `images` folder don't match this mockup. Which to use?
2. I used a fontmatter captions for now. Am I right?
3. I want to make a service index page according to the mockup and change some styles on the frontpage to match this mockup as well (frontpage styles are slightly different now)

**Comment by lakruzz** [comment]
1) You can use the pictures from Tenna's mock-up - they are prettier than mine :+1:  (it's not _very_ important at this point, we will go through to content and pics later)

2) Yes

3) Fine - go ahead :+1:

**Comment by illus0r** [comment]
@lakruzz Delivered!

**Comment by lakruzz** [comment]
Fine, great job!

Please - make it a habit to mention the issue in your commit messages, so we get a reference to the commits that contributed to this issus.


let's continue on #59
