### ISSUE TITLE
Services - subpage

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#59]
We need some lay-out on the services subpage

(e.g. http://new.praqma.com/services/assessments/)

It could be a right sidebar with access to the other services pages in a small index - some level of both improved usability and eye candy is required.

Give it a shot!

**Comment by illus0r** [comment]
@lakruzz delivered, how do you like it?
![image](https://cloud.githubusercontent.com/assets/797993/11214436/4ed41560-8d52-11e5-85f1-6a602a5baf3c.png)

**Comment by lakruzz** [comment]
Maybe I'd like it to be somewhat more visual - and less _wall og text_ the tha avatars/icon images from the service pages be part of each menu item some how?

What do you think?

**Comment by illus0r** [comment]
@lakruzz great, I have an idea about how to implement this.

**Comment by illus0r** [comment]
@lakruzz 
Looks like this 

![image](https://cloud.githubusercontent.com/assets/797993/12118223/47baaf14-b3d6-11e5-81b4-0f7afcc250d6.png)

**Comment by illus0r** [comment]
On mobile the menu goes after the main content

![image](https://cloud.githubusercontent.com/assets/797993/12118354/0ef875c0-b3d7-11e5-801b-d06877eb5189.png)

**Comment by lakruzz** [comment]
Very nice - I'm closing :+1:
