### ISSUE TITLE
Training index

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#60]
![image](https://cloud.githubusercontent.com/assets/155492/11184270/efcb70c6-8c76-11e5-86d7-198b2a71d2e1.png)

Could we try to get the index of the training left menu bar closer to the original mockup:

![image](https://cloud.githubusercontent.com/assets/155492/11184155/5cbc0048-8c76-11e5-8b85-3f23c0328ec5.png)

- [ ] Menu items that aren't selected at semi-transparent
- [ ] Menu items are perfect squares
- [ ] Menu item graphics does not have borders
- [ ] The selected menu item is marked with a fat orange undelines (like in the menu bar)
- [ ] The selected menu item is not transparent

**Comment by illus0r** [comment]
@lakruzz made two subtasks #63 and #64

**Comment by lakruzz** [comment]
Duplicate of #63
