### ISSUE TITLE
About us - Index page

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#61]
The About us menu is an index with 4 sub pages

- People
- Offices
- Partners
- Jobs

The mock up looks like this:
![image](https://cloud.githubusercontent.com/assets/155492/11207328/ea253ed8-8d14-11e5-9cff-d8430192ef68.png)

I would like you to load the pages dynamically: That is, look for subpages and load the ones you find (as with the training subpages) - I'll upload som sample markdown that explains what I mean.

**Comment by lakruzz** [comment]
@illus0r Iv'e added som copy and samples - let me know if it makes sense

**Comment by monaslarsen** [comment]
![offices](https://cloud.githubusercontent.com/assets/13627068/11213426/4e0a9f98-8d3c-11e5-830c-c632ec9f6c6f.png)
![ikoner-01](https://cloud.githubusercontent.com/assets/13627068/11213428/4e0dcc2c-8d3c-11e5-831e-004cb794999c.png)
![jobs](https://cloud.githubusercontent.com/assets/13627068/11213427/4e0ad508-8d3c-11e5-981f-c8a2db93123f.png)
[Ikoner.pdf](https://github.com/Praqma/praqma.github.io/files/36732/Ikoner.pdf)
![partners](https://cloud.githubusercontent.com/assets/13627068/11213429/4e10e628-8d3c-11e5-9ec7-9688be8fc0f7.png)

**Comment by monaslarsen** [comment]
![offices](https://cloud.githubusercontent.com/assets/13627068/11213459/766b5dd8-8d3c-11e5-8f6c-3b49e5a06eaa.png)
![ikoner-01](https://cloud.githubusercontent.com/assets/13627068/11213458/766a83a4-8d3c-11e5-9772-291408a2e530.png)
![jobs](https://cloud.githubusercontent.com/assets/13627068/11213461/766ee976-8d3c-11e5-89bf-c7bc47baf993.png)
![partners](https://cloud.githubusercontent.com/assets/13627068/11213460/766e3fd0-8d3c-11e5-92d4-3094a25fe4a1.png)

**Comment by illus0r** [comment]
Hey, @lakruzz! What do you mean by *dynamically*? Should we use an ajax or just automate menu generation like I did for *services* and *blog*?

**Comment by illus0r** [comment]
i'm pretty sure you didn't mean an *ajax*, I've asked just in case

**Comment by illus0r** [comment]
@lakruzz I've made a first approach, now *about* index looks like on the pic. Which text do we need? From the `.md` file or from the mockup? I'm going to style the text after your feedback.
![image](https://cloud.githubusercontent.com/assets/797993/11241845/fda839ec-8e0e-11e5-8fc1-91ae4c423fd2.png)

**Comment by illus0r** [comment]
And, I've noticed the titles on the menu and on the page (marked up by markdown) are different. Ex. *PARTNERS* link brings us to *OUR LOVELY CLIENTS*. I'd recommend to use the same names for both in order not to confuse a visitor. So I didn't remove first title from a template yet, now it's like on the pic
![image](https://cloud.githubusercontent.com/assets/797993/11242051/5d1096da-8e10-11e5-89fd-3ca8e03c8e86.png)

**Comment by lakruzz** [comment]
@illus0r 
Right, so partners should be partners and customer should be customers :+1: It's just me being too quick on the save-as function :-)

What I meant by dynamically is that I don't know if we will _always_ have exactly 4 elements on this page - it might be more or or less.  I just want you to load the pages you find - in rows of 4, then we'll have to manage it on the content side.

It would be great if you could generate the customer subpage and the partner subpage based on parsing the two data files.

I have create cases #69 and #70 for this
