### ISSUE TITLE
Offices sub-page

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#62]
![image](https://cloud.githubusercontent.com/assets/155492/11207497/daf51dec-8d15-11e5-8e2c-305fb8bf8ba0.png)

**Comment by adamhenriques** [comment]
Lars,

Vil det ikke give mening at tilføje Stockholm kontor for at vise vores
tilstedeværelse?

[image: ____________________________________________________________]
Adam Henriques
Sales & Marketing
ah@praqma.net
+45 28 12 90 94 <+45%2028%2012%2090%2094>
Skype: adamhenriques
Praqma
www.praqma.com
CPH, OSL, STHLM
+45 36 PRAQMA <+4536772762>
<http://www.code-conf.com/day-of-docker-osl15/?src=mailbanner>

**Comment by lakruzz** [comment]
Yes! And to eave out the office in Malmö, where we actually don't have an office :-)

**Comment by lakruzz** [comment]
I've added a list of offices in `/_data/offices.yml`

**Comment by illus0r** [comment]
Sometimes on the mockup I see VAT, sometimes CVR/VAT. What to use?

**Comment by illus0r** [comment]
@lakruzz and we can make maps even greater. I't hard to operate in a stamp-sized window.
![image](https://cloud.githubusercontent.com/assets/797993/11268971/f98e0966-8ec4-11e5-8f3d-ed6568cc1b82.png)

**Comment by illus0r** [comment]
and, sure, we can
![image](https://cloud.githubusercontent.com/assets/797993/11269067/ce811adc-8ec5-11e5-8672-4db3fb922dee.png)

**Comment by illus0r** [comment]
Or combined case:
![image](https://cloud.githubusercontent.com/assets/797993/11269214/b0687b3e-8ec6-11e5-83c7-f5581b4200d7.png)

**Comment by lakruzz** [comment]
I Like option ![option 2](https://cloud.githubusercontent.com/assets/797993/11269067/ce811adc-8ec5-11e5-8672-4db3fb922dee.png) better
