### ISSUE TITLE
Training menu: make a mockup with training titles closer to original

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#63]
Subtask of #60
![image](https://cloud.githubusercontent.com/assets/155492/11184270/efcb70c6-8c76-11e5-86d7-198b2a71d2e1.png)

Could we try to get the index of the training left menu bar closer to the original mockup:

![image](https://cloud.githubusercontent.com/assets/155492/11184155/5cbc0048-8c76-11e5-8b85-3f23c0328ec5.png)

**Comment by illus0r** [comment]
@lakruzz what do you like in mockup? It's not clear to me for now, how to keep square form and put the labels into squares and to keep them legible. May be I'm solving an unnecessary task and you'll correct my task vision. 

Hmm, we can show labels on mouse hover thought. But not for iPads.

![img](https://cloud.githubusercontent.com/assets/155492/11184155/5cbc0048-8c76-11e5-8b85-3f23c0328ec5.png)

**Comment by lakruzz** [comment]
I get your point.

The oragen line in the buttom is what is indicating which tile is selected.

But to begin with, could you simply make them look more like tiles, so that the border isn't just around the image, but includes the image caption

**Comment by illus0r** [comment]
@lakruzz I'm not satisfied with current result, but decided to publish to get feedback.
Works on different sizes. Some tiles should have more crispy edges when active
![image](https://cloud.githubusercontent.com/assets/797993/12295252/f26c5738-ba10-11e5-951c-9682038f57ee.png)

**Comment by illus0r** [comment]
ouch, I've commited with `#62` in comment.

**Comment by lakruzz** [comment]
I think we'll wrap it up for now.

give @monaslarsen and @meekrosoft a chance to comment, and if they don't object, let's ship tis for the MVP
