### ISSUE TITLE
Add copy for partners

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#66]
The information about all our customers should be added to

https://github.com/Praqma/praqma.github.io/blob/master/_data/partners.yml

in the format:

    -
      company:
      url:
      logo:
      caption:

- [ ] All logos should be put in the folder /images/partners/
- [ ]  All logos should be in .png
- [ ]  All logos shall be in the format 2:1 (width:height)

**Comment by meekrosoft** [comment]
Other than docker, who do we add?

**Comment by meekrosoft** [comment]
Right now the yaml is in line in the partners.md.  Should this be moved to the yaml file in _data?

**Comment by meekrosoft** [comment]
I have added docker to the page
