### ISSUE TITLE
Tags on blogs - we need a plan!

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#67]
Exemplified in `http://new.praqma.com/blog/linkckecker-jekyll-flavor/`

![image](https://cloud.githubusercontent.com/assets/155492/11212582/ff897f06-8d36-11e5-8605-0d77a6b32b68.png)

There are tags on the blog post that I cant click on:

![image](https://cloud.githubusercontent.com/assets/155492/11212604/20f23d18-8d37-11e5-9d46-0103efe48e88.png)

We need a strategy for how to get this to work.

**Comment by illus0r** [comment]
@lakruzz if a blog post uses a tag that's not presented by corresponding `tag-page` file, I show it anyway, but in gray. If you want to make `http://new.praqma.com/blog/linkckecker-jekyll-flavor/`'s tags clickable, add a `_tag-pages/Jekyll.html` and so on.

**Comment by illus0r** [comment]
Should I add all necessary tag-pages?

**Comment by lakruzz** [comment]
@illus0r 

Hold on for this one - I'm might have a suggestion I'd like to make - an hour or two - and I'll be back...
