### ISSUE TITLE
Blog index on tags interfeers with posts

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#68]
Using `http://localhost:4000/blog/markdown/` as an example:

![image](https://cloud.githubusercontent.com/assets/155492/11212665/893b7c04-8d37-11e5-8ba5-0edda242a617.png)

This page is an index of all the posts tagged with _markdown_  but it also means that the the index and the posts are now competing ofr this namespace.

Imagine I had a blog post named "MarkDown" - they wouldn't be able to co-exist!!!

Maybe the indexes should go to a permalink unde `tag` so that in `_config.yml` the collection setting for tag-pages is:

    collections:
      tag-pages:
        output: true
        permalink: /blog/tag/:path/

**Comment by illus0r** [comment]
@lakruzz set medium size, because of possible complications with an active menu item highlighting. But I hope, I'll do it much faster. Should I set `small` instead?
