### ISSUE TITLE
Create customers sub page

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#69]
A spin off from #61 
![image](https://cloud.githubusercontent.com/assets/155492/11267042/3faa5312-8ea9-11e5-9a72-1a2f9280bba3.png)

- [ ] The subpages under about us, should have a right side-bar wit easy access to the other about sub pages

**Comment by lakruzz** [comment]
We need a page with the same purpose as http://www.praqma.com/Customers

And we need the info that generates it to be editable from the yaml file

**Comment by illus0r** [comment]
> The subpages under about us, should have a **right** side-bar wit easy access to the other about sub pages

@lakruzz On the other pages menu is on the left. I'll do the same here. However, if you want to move it right, I'll do it easily.

**Comment by illus0r** [comment]
@lakruzz should I use client logo list from praqma.com?

**Comment by illus0r** [comment]
I've finished collecting logos (asked a freelancer to help me finding bigger logos from http://www.praqma.com/Customers list)
And have put some styles on. I'm already out of a timebox, but I need time for a side menu. I know, that's not good, but I forgot about this part of task :grimacing:

**Comment by illus0r** [comment]
@lakruzz now it's like this
![image](https://cloud.githubusercontent.com/assets/797993/11994241/1a5ca61e-aa4c-11e5-96ca-b31aaa2b97e4.png)

**Comment by illus0r** [comment]
Can we close?

**Comment by lakruzz** [comment]
Looks fine, I'm closing it :+1:
