### ISSUE TITLE
Make menu markup semantic

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#7]
Just to clean up a code of nav.html include file to remove bootstrap classes like `nav navbar-nav` and so on.
Maybe the task is not necessary, I made it just not to forget

**Comment by MadsNielsen** [comment]
@lakruzz do you get this?

**Comment by lakruzz** [comment]
@illus0r 
You need to add a more thorough description - Based on your header I don't know what this issue is about, so I can't put prio on it.

Please 
- [] fill in the description field
- [] Remove the "Action - needs grooming" label
- [] Assign it back to me
