### ISSUE TITLE
Create Partners sub page

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#70]
A spinn off from #61

![image](https://cloud.githubusercontent.com/assets/155492/11267090/86ecfebe-8ea9-11e5-8d62-5f917c540807.png)

related (similar) to  #69

**Comment by illus0r** [comment]
@lakruzz 
what's difference from #69?

**Comment by lakruzz** [comment]
one is partners, another is customers...

**Comment by illus0r** [comment]
to be styled in #94
