### ISSUE TITLE
Repair menu on mobile (should be inline-block on desktop only)

### ISSUE THREAD

**Issue by illus0r** [Praqma/praqma.github.io#8]
Now mobile menu occupies two or more lines on small screen. That's bad, If we need subnemus.

The task can be labeled "won't have" until we need a submenu system.

![image](https://cloud.githubusercontent.com/assets/797993/10786920/31c323be-7d7e-11e5-982d-36b8b66cd08c.png)

**Comment by lakruzz** [comment]
@illus0r 
You need to add a more thorough description - Based on your header I don't know what this issue is about, so I can't put prio on it.

Please 
- [ ] fill in the description field
- [ ] Remove the "Action - needs grooming" label
- [ ] Assign it back to me

**Comment by illus0r** [comment]
@lakruzz let's close it. We will make a independent task when we need a dropdown menus
