### ISSUE TITLE
Copy for About/ Jobs

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.github.io#85]

**Comment by lakruzz** [comment]
@buep has written a short draft for a part time student employee to manage our IT at all sites, please share with @meekrosoft and let's get this online too

**Comment by buep** [comment]
@meekrosoft find my draft here: https://docs.google.com/document/d/1xQxlTmULYcEUnI9P1Aa8guiw4g2JNjqp49kiZ9WxEmM/edit

Shared with Praqma org.

Let me know when we are ready... input on the announcement is very welcome... think it was hard to write actually.

**Comment by meekrosoft** [comment]
Added with commit 5757450c73e4e17f80959fb23f3c6a388e4a8f45

Would love some feedback!  Can see it here: http://new.praqma.com/about/jobs/ops-student/

**Comment by buep** [comment]
I think it is perfect... nice changed you did to my draft :-)

We could maybe add a skill around good network understanding... as there will be quite some work around this. But if it scares students away... don't. I think the most important things are covered.
