### ISSUE TITLE
Caption is too large

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.github.io#88]
![image](https://cloud.githubusercontent.com/assets/13627068/11423752/66020336-9447-11e5-8a0f-2dab0d5b3c65.png)

The Caption text on the training page is too large.

**Comment by monaslarsen** [comment]
@lakruzz do you agree?

**Comment by lakruzz** [comment]
Ivan we need to beautify the use of fonts in general.

- [ ] The caption should be same size as body text - only in difference is that it should  be bold-face.
- [ ] On the blog posts, the body text is grey - i think it's too light

![image](https://cloud.githubusercontent.com/assets/155492/12194188/45a24c9a-b5ee-11e5-8929-c1294e1506f8.png)

**Comment by lakruzz** [comment]
@illus0r please estimate this one - I assume it's small! right?

**Comment by illus0r** [comment]
Why not to make blog text `#333333`? 

![image](https://cloud.githubusercontent.com/assets/797993/12198547/116bc9a4-b622-11e5-96c5-1d03809d79b6.png)

**Comment by lakruzz** [comment]
Fine!
