### ISSUE TITLE
Create markdown files of blog posts from old praqma.com

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.github.io#89]

**Comment by lakruzz** [comment]
![image](https://cloud.githubusercontent.com/assets/155492/12197253/ca5ef46c-b605-11e5-9997-75e08585ce03.png)

**Comment by lakruzz** [comment]
This is an ongoing process - Ill close this on in the context of MVP and we can create new ones as we go forward - we will have to monitor google analytics
