### ISSUE TITLE
Come up with document format design

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#9]
I think we support a one-page design that _can_ be extended with sub-pages

In which case a TOC should be automatically generated.

Examples of the current design are available in:

* http://www.2git.io
* http://code.praqma.com/mailsignature/ 
* http://code.praqma.com/MonKit-Plugin
* http://code.praqma.com/ghreport/

**Comment by lakruzz** [comment]
@JKrag @buep @MadsNielsen @groenborg @kryptag @martinmosegaard @praqma-thi 

Feedback is welcome - I'd like to bring this issue up with @jonnycoull and @kryptag in the Design Workshop I have with them next week.

If you have _any_ opinions or input to this topic before then - let us know in this issue here

**Comment by buep** [comment]
Not much input from my side, except make it reusable and configurable so common parts can be shared and maintain in one place. Not sure how you do it with the tech we use, but we figure it out.

Else I'm thinking we need the setup to include different parts of docs in a clever way like user docs, design docs, architecture, roadmaps, developer info etc.

Looking forward to see what you come up with. Anything common that is easy to adjust will be a big step forward  I think.

**Comment by praqma-thi** [comment]
I found the drill-down single pages to be rather limiting.
Supporting a sidebar and adding some more orange wouldn't hurt at all.

**Comment by jonnycoull** [comment]
@lakruzz we didn't get round to this we should have a hang out.

**Comment by lakruzz** [comment]
Closing this one - @kryptag is currently working on a solution in josra/josra.github.io#33 (and more) we will reuse that when it's done
