### ISSUE TITLE
Adjust sizes of headline levels

### ISSUE THREAD

**Issue by monaslarsen** [Praqma/praqma.github.io#90]
Right now, level 3 headlines are bigger than level 2 headlines

**Comment by illus0r** [comment]
Came up with this. Looks pretty good on all pages excepting this one

![image](https://cloud.githubusercontent.com/assets/797993/12117030/f87c94c8-b3ce-11e5-805f-62c9579b127c.png)

**Comment by lakruzz** [comment]
looking fine - I'm closing it.
