### ISSUE TITLE
Style our 404 page

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#96]

**Comment by illus0r** [comment]
@lakruzz 
I'm going to

* [ ] Change text to help a visitor to find a page he need.
* [ ] Add a search form to google through the site.

**Comment by illus0r** [comment]
@lakruzz, text may require some improvement. I tried not to leave your potential client face to face with a problem, but suggest a solution.

![image](https://cloud.githubusercontent.com/assets/797993/12392678/bf0d8700-be01-11e5-9350-d25e63282984.png)

**Comment by lakruzz** [comment]
Fine

- [ ] Please refer to the blog as "stories" instead (Blog is not used anywhere anymore) 
- [ ] _Serach_ should be spelled __Search__
