### ISSUE TITLE
Blog posts: All tags should work

### ISSUE THREAD

**Issue by lakruzz** [Praqma/praqma.github.io#97]
Currently only some of the tags in blogs are clickable, and tag pages must be manually generated.

All tags must work automatically.

I had had this  working in an early version on code-maturity using cgi and js.

**Comment by illus0r** [comment]
@lakruzz 
So I'm going to implement your previous solution. I'll use a single page with a `js` driven filtering.

**Comment by illus0r** [comment]
I'll use `window.location.hash` and make urls like `http://localhost:3000/blog/#newest`

**Comment by illus0r** [comment]
I'll take 4 hours for timebox and let you know the result

**Comment by lakruzz** [comment]
Hi @illus0r what's status on this one? Is it still labeled work in progress?

**Comment by illus0r** [comment]
@lakruzz i spent few time on work last days, I want to speed up now. I've looked for a ready plugin for implementing this task, tryed [Isotope](http://isotope.metafizzy.co/), but it brings a lot of unnecessary stuff like *masonry* and + 5 other libraries.

So I decided to write `js` myself. 

But I just thought about finding and customizing your ready script

**Comment by illus0r** [comment]
necessary improvements:
- [ ] Scroll to top after reload
- [ ] Activate tag links on post pages
- [ ] Highlight active tag links
- [ ] Handle wrong hash values

**Comment by lakruzz** [comment]
Regarding handling wrong hashes, simply let the 404 page handle it

**Comment by lakruzz** [comment]
Looks fine - doesn't seem that we're that for out

**Comment by illus0r** [comment]
@lakruzz pushed and testable on http://new.praqma.com/
didn't implement *Sort tag list alphabetically*, I'll make it a separate task
